---
title: "Construal Level International Multilab Replication (CLIMR) Project: Validation Pretest Report"
author: "CLIMR Team"
date: "`r Sys.Date()`"
output:
  html_document:
    theme: darkly
    toc: yes
    toc_float: yes
  pdf_document:
    toc: yes
knit: (function(input_file, encoding) {
    rmarkdown::render(input_file, encoding = encoding, output_dir = "./reports/")
  })
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

source("./R/validation/CLIMR-validation_data_importation.R")
source("./R/validation/CLIMR-validation_effect_calculations.R")
source("./R/validation/CLIMR-validation_data_visualization.R")

```

# Categorization Task

```{r}
effect_temporal
```

```{r}
temporal_hist
```

# Segmentation Task

```{r}
effect_spatial
```

```{r}
spatial_hist
```

# Behavior Identification Form

```{r}
effect_temporal_2
```

```{r}
temporal_2_hist
```

# Robustness Checks

## Categorization Task

```{r}
effect_temporal_cc
```

## Segmentation Task

```{r}
effect_spatial_cc
```

## Behavior Identification Form

```{r}
effect_temporal_2_cc
```
