---
title: "Construal Level International Multilab Replication (CLIMR) Project: Robustness Tests Account for Valence Differences in the Response Options for the Items on the Behavior Identification Form (BIF)"
author: "CLIMR Team"
date: "`r Sys.Date()`"
output:
  html_document:
    theme: darkly
    toc: yes
    toc_float: yes
    keep_md: true
  pdf_document:
    toc: yes
knit: (function(input_file, encoding) {
    rmarkdown::render(input_file, rmarkdown::github_document(html_preview = FALSE), encoding = encoding, output_dir = "./reports/")
  })
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```

# **THESE RESULTS ARE SIMULATED. DO NOT INTERPRET.**

# Liberman & Trope (1998, Study 1)

```{r}
lrt_val_temporal
```

```{r}
summary(glmm_temporal_bif_base)
```

```{r}
summary(glmm_temporal_bif_val)
```

```{r}
summary(glmm_temporal_bif_int)
```

# Fujita et al. (2006, Study 1)

```{r}
lrt_val_spatial
```

```{r}
summary(glmm_spatial_bif_base)
```

```{r}
summary(glmm_spatial_bif_val)
```

```{r}
summary(glmm_spatial_bif_int)
```

# Social Distance (Paradigmatic Replication)

```{r}
lrt_val_social
```

```{r}
summary(glmm_social_bif_base)
```

```{r}
summary(glmm_social_bif_val)
```

```{r}
summary(glmm_social_bif_int)
```

# Likelihood Distance (Paradigmatic Replication)

```{r}
lrt_val_likelihood
```

```{r}
summary(glmm_likelihood_bif_base)
```

```{r}
summary(glmm_likelihood_bif_val)
```

```{r}
summary(glmm_likelihood_bif_int)
```
