---
title: "Construal Level International Multilab Replication (CLIMR) Project: Exploration of Country and Language as Random Effects"
author: "CLIMR Team"
date: "`r Sys.Date()`"
output:
  html_document:
    theme: darkly
    toc: yes
    toc_float: yes
    keep_md: true
  pdf_document:
    toc: yes
knit: (function(input_file, encoding) {
    rmarkdown::render(input_file, rmarkdown::github_document(html_preview = FALSE), encoding = encoding, output_dir = "./reports/")
  })
---

# Liberman & Trope (1998, Study 1)

```{r}
meta_temporal_country
```

```{r}
ranef_temporal_country
```

```{r}
meta_temporal_language
```

```{r}
ranef_temporal_language
```

# Fujita et al. (2006, Study 1)

```{r}
meta_spatial_country
```

```{r}
ranef_spatial_country
```

```{r}
meta_spatial_language
```

```{r}
ranef_spatial_language
```

# Social Distance (Paradigmatic Replication)

```{r}
meta_social_country
```

```{r}
ranef_social_country
```

```{r}
meta_social_language
```

```{r}
ranef_social_language
```

# Likelihood Distance (Paradigmatic Replication)

```{r}
meta_likelihood_country
```

```{r}
ranef_likelihood_country
```

```{r}
meta_likelihood_language
```

```{r}
ranef_likelihood_language
```