---
title: "Construal Level International Multilab Replication (CLIMR) Project: Robustness Tests Accounting for Valence Differences in the Response Options for the Items on the Behavior Identification Form (BIF) -- (1) random slopes for labs and BIF items, (2) for the Full BIF Scale, and (3) Item Removal for the Interaction Observed for the Temporal Distance Experiment"
author: "CLIMR Team"
date: "`r Sys.Date()`"
output:
  html_document:
    theme: darkly
    toc: yes
    toc_float: yes
    keep_md: true
  pdf_document:
    toc: yes
knit: (function(input_file, encoding) {
    rmarkdown::render(input_file, rmarkdown::github_document(html_preview = FALSE), encoding = encoding, output_dir = "./reports/")
  })
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```

# Random Slopes Models

## Liberman & Trope (1998, Study 1)

```{r}
lrt_val_temporal_rs
```

```{r}
summary(glmm_temporal_bif_base_rs)
```

```{r}
summary(glmm_temporal_bif_val_rs)
```

```{r}
summary(glmm_temporal_bif_int_rs)
```

## Fujita et al. (2006, Study 1)

```{r}
lrt_val_spatial_rs
```

```{r}
summary(glmm_spatial_bif_base_rs)
```

```{r}
summary(glmm_spatial_bif_val_rs)
```

```{r}
summary(glmm_spatial_bif_int_rs)
```

## Social Distance (Paradigmatic Replication)

```{r}
lrt_val_social_rs
```

```{r}
summary(glmm_social_bif_base_rs)
```

```{r}
summary(glmm_social_bif_val_rs)
```

```{r}
summary(glmm_social_bif_int_rs)
```

## Likelihood Distance (Paradigmatic Replication)

```{r}
lrt_val_likelihood_rs
```

```{r}
summary(glmm_likelihood_bif_base_rs)
```

```{r}
summary(glmm_likelihood_bif_val_rs)
```

```{r}
summary(glmm_likelihood_bif_int_rs)
```

# Analysis of Full BIF (All Items)

## Liberman & Trope (1998, Study 1)

```{r}
lrt_val_temporal_full
```

```{r}
summary(glmm_temporal_bif_base_full)
```

```{r}
summary(glmm_temporal_bif_val_full)
```

```{r}
summary(glmm_temporal_bif_int_full)
```

## Fujita et al. (2006, Study 1)

```{r}
lrt_val_spatial_full
```

```{r}
summary(glmm_spatial_bif_base_full)
```

```{r}
summary(glmm_spatial_bif_val_full)
```

```{r}
summary(glmm_spatial_bif_int_full)
```

## Likelihood Distance (Paradigmatic Replication)

```{r}
lrt_val_likelihood_full
```

```{r}
summary(glmm_likelihood_bif_base_full)
```

```{r}
summary(glmm_likelihood_bif_val_full)
```

```{r}
summary(glmm_likelihood_bif_int_full)
```

# Temporal Distance: Removing Item with Smallest Valence Difference

```{r}
lrt_val_temporal_rem
```

```{r}
summary(glmm_temporal_bif_base_rem)
```

```{r}
summary(glmm_temporal_bif_val_rem)
```

```{r}
summary(glmm_temporal_bif_int_rem)
```
