---
title: "Construal Level International Multilab Replication (CLIMR) Project: Analysis of Study Duration as a Moderator"
author: "CLIMR Team"
date: "`r Sys.Date()`"
output:
  html_document:
    theme: darkly
    toc: yes
    toc_float: yes
    keep_md: true
  pdf_document:
    toc: yes
knit: (function(input_file, encoding) {
    rmarkdown::render(input_file, rmarkdown::github_document(html_preview = FALSE), encoding = encoding, output_dir = "./reports/")
  })
---

# Study Duration

Note that these analyses only include data from participants whose recorded
duration was one hour or less.

## Liberman & Trope (1998, Study 1)

```{r}
lrt_dur_temporal
```

```{r}
summary(glmm_temporal_dur_base)
```

```{r}
summary(glmm_temporal_dur_add)
```

```{r}
summary(glmm_temporal_dur_int)
```

## Fujita et al. (2006, Study 1)

```{r}
lrt_dur_spatial
```

```{r}
summary(glmm_spatial_dur_base)
```

```{r}
summary(glmm_spatial_dur_add)
```

```{r}
summary(glmm_spatial_dur_int)
```

## Social Distance (Paradigmatic Replication)

```{r}
lrt_dur_social
```

```{r}
summary(glmm_social_dur_base)
```

```{r}
summary(glmm_social_dur_add)
```

```{r}
summary(glmm_social_dur_int)
```

## Likelihood Distance (Paradigmatic Replication)

```{r}
lrt_dur_likelihood
```

```{r}
summary(glmm_likelihood_dur_base)
```

```{r}
summary(glmm_likelihood_dur_add)
```

```{r}
summary(glmm_likelihood_dur_int)
```
