---
title: "Construal Level International Multilab Replication (CLIMR) Project: Main Analysis Report"
author: "CLIMR Team"
date: "`r Sys.Date()`"
output:
  html_document:
    theme: darkly
    toc: yes
    toc_float: yes
  pdf_document:
    toc: yes
knit: (function(input_file, encoding) {
    rmarkdown::render(input_file, encoding = encoding, output_dir = "./reports/")
  })
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# Simulate (replace with data importation) ----------------------------

source("./R/simulate/CLIMR_simulation.R")

# Calculate effect sizes and conduct meta-analyses --------------------

source("./R/calculate/CLIMR_calculate_effects.R")
source("./R/analyze/CLIMR_main_analyses.R")

```

# Main Figure

```{r, fig.asp = 1/1.6, fig.width = 5 * 2}
climr_figure
```


# Meta-Analytic Models

## Liberman et al (2002, Study 1)

```{r}
meta_temporal
```

## Liberman & Trope (1998, Study 1)

```{r}
meta_temporal_2
```

## Henderson et al. (2006, Study 1)

```{r}
meta_spatial
```

## Wakslak et al. (2006, Study 1)

```{r}
meta_likelihood
```

## Simultaneous Analysis

```{r}
meta_complete
```

```{r}
I2_complete
```

# Arboretum

```{r, fig.height = 12, fig.width = 18}
arboretum
```



