---
title: "Construal Level International Multilab Replication (CLIMR) Project: Analysis of Positive and Negative Affect (PANAS)"
author: "CLIMR Team"
date: "`r Sys.Date()`"
output:
  html_document:
    theme: darkly
    toc: yes
    toc_float: yes
    keep_md: true
  pdf_document:
    toc: yes
knit: (function(input_file, encoding) {
    rmarkdown::render(input_file, rmarkdown::github_document(html_preview = FALSE), encoding = encoding, output_dir = "./reports/")
  })
---

# Positive and Negative Affect (PANAS)

## Liberman & Trope (1998, Study 1)

```{r}
lrt_panas_temporal
```

```{r}
summary(glmm_temporal_panas_base)
```

```{r}
summary(glmm_temporal_panas_add)
```

```{r}
summary(glmm_temporal_panas_int)
```

```{r}
lrt_panas_val_temporal
```
```{r}
summary(glmm_temporal_panas_val)
```

## Fujita et al. (2006, Study 1)

```{r}
lrt_panas_spatial
```

```{r}
summary(glmm_spatial_panas_base)
```

```{r}
summary(glmm_spatial_panas_add)
```

```{r}
summary(glmm_spatial_panas_int)
```

```{r}
lrt_panas_val_spatial
```

```{r}
summary(glmm_spatial_panas_val)
```

## Social Distance (Paradigmatic Replication)

```{r}
lrt_panas_social
```

```{r}
summary(glmm_social_panas_base)
```

```{r}
summary(glmm_social_panas_add)
```

```{r}
summary(glmm_social_panas_int)
```

```{r}
lrt_panas_val_social
```

```{r}
summary(glmm_social_panas_val_int)
```

```{r}
summary(glmm_social_panas_val_int_3)
```

## Likelihood Distance (Paradigmatic Replication)

```{r}
lrt_panas_likelihood
```

```{r}
summary(glmm_likelihood_panas_base)
```

```{r}
summary(glmm_likelihood_panas_add)
```

```{r}
summary(glmm_likelihood_panas_int)
```

```{r}
lrt_panas_val_likelihood
```

```{r}
summary(glmm_likelihood_panas_val)
```
